// Каталог игр клуба ART-VR. Сгенерировано из games.json скриптом
// scripts/generate-games.py — правки вносите в games.json.

export type GameGenre =
  | 'shooter'
  | 'horror'
  | 'quest'
  | 'sport'
  | 'rhythm'
  | 'sim'
  | 'party'
  | 'relax'
  ;

export type GamePlatform = 'pc' | 'standalone';

export interface Game {
  title: string;
  slug: string;
  description: string;
  genre: GameGenre;
  platforms: GamePlatform[];
  players: string;
  age: string;
  playtime: string;
  maxPlayers: number;
  /** Популярность 0–100: каталог отсортирован по ней. */
  popularity: number;
  image?: string;
  /** Обложка 600×750 для страницы игры. */
  cover?: string;
  youtube?: string;
}

export const genreLabels: Record<GameGenre, string> = {
  shooter: 'Шутеры и бои',
  horror: 'Хорроры',
  quest: 'Приключения и квесты',
  sport: 'Спорт',
  rhythm: 'Ритм и музыка',
  sim: 'Симуляторы',
  party: 'Настолки и стратегии',
  relax: 'Аттракционы и релакс',
};

export const platformLabels: Record<GamePlatform, string> = {
  pc: 'ПК-VR',
  standalone: 'На шлемах',
};

export const games: Game[] = [
  {
    title: 'Beat Saber',
    slug: 'beat-saber',
    description:
      'Beat Saber — культовый VR-ритм-экшен, в котором нужно рассекать световыми мечами разноцветные блоки в такт музыке, уклоняясь от препятствий и стен. Жанр — ритм-игра/аркада. Атмосфера энергичная и музыкальная, отлично подходит для новичков в VR.',
    genre: 'rhythm',
    platforms: ['pc'],
    players: '1-5',
    age: '6',
    playtime: '20-40',
    maxPlayers: 5,
    popularity: 100,
    image: '/images/games/beat-saber.jpg',
    cover: '/images/games/covers/beat-saber.jpg',
    youtube: 'https://www.youtube.com/watch?v=vL39Sg2AqWg',
  },
  {
    title: 'Gorilla Tag',
    slug: 'gorilla-tag',
    description:
      'Многопользовательская VR-игра, в которой персонаж передвигается по уровням, отталкиваясь руками от поверхностей, как настоящая горилла — без единой кнопки телепорта. Казуальная социальная игра в духе салочек с несколькими режимами и большим открытым онлайн-сообществом.',
    genre: 'sport',
    platforms: ['pc'],
    players: '1-10',
    age: '8',
    playtime: '10-15',
    maxPlayers: 10,
    popularity: 100,
    image: '/images/games/gorilla-tag.jpg',
    cover: '/images/games/covers/gorilla-tag.jpg',
    youtube: 'https://www.youtube.com/watch?v=y3bR3s546CU',
  },
  {
    title: 'Phasmophobia',
    slug: 'phasmophobia',
    description:
      'Phasmophobia — кооперативный психологический хоррор, в котором команда охотников за привидениями исследует заброшенные локации, собирает улики с помощью специального оборудования и определяет тип паранормальной активности. Атмосфера крайне напряжённая: тусклый свет, шорохи и внезапные атаки призрака держат игроков в постоянном страхе. Поддерживается игра от 1 до 4 человек, доступна как в VR, так и на обычном экране.',
    genre: 'horror',
    platforms: ['pc'],
    players: '1-4',
    age: '12',
    playtime: '30-60',
    maxPlayers: 4,
    popularity: 99,
    image: '/images/games/phasmophobia.jpg',
    cover: '/images/games/covers/phasmophobia.jpg',
    youtube: 'https://www.youtube.com/watch?v=sRa9oeo5KiY',
  },
  {
    title: 'Pavlov VR',
    slug: 'pavlov-vr',
    description:
      'Pavlov VR — мультиплеерный VR-шутер от первого лица в духе CS:GO, с реалистичной физикой оружия и ручной перезарядкой. Есть режимы «Поиск и уничтожение», Deathmatch, Zombies, King of the Hill, а также контент времён Второй мировой войны. Атмосфера динамичная и соревновательная, ориентирована на командную игру и голосовой чат.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1-10',
    age: '12',
    playtime: '30-60',
    maxPlayers: 10,
    popularity: 97,
    image: '/images/games/pavlov-vr.jpg',
    cover: '/images/games/covers/pavlov-vr.jpg',
    youtube: 'https://www.youtube.com/watch?v=9PFzOZ8j75M',
  },
  {
    title: 'The Forest',
    slug: 'the-forest',
    description:
      'The Forest — survival-хоррор с видом от первого лица, где герой выживает на загадочном острове после крушения самолёта, строит укрытия и обороняется от каннибалов-мутантов. Жанр — survival/хоррор с элементами крафта. Атмосфера мрачная и напряжённая, с открытым миром и постоянным чувством угрозы.',
    genre: 'horror',
    platforms: ['pc'],
    players: '1-8',
    age: '12',
    playtime: '30-60',
    maxPlayers: 8,
    popularity: 93,
    image: '/images/games/the-forest.jpg',
    cover: '/images/games/covers/the-forest.jpg',
    youtube: 'https://www.youtube.com/watch?v=7mwn5U2PNvk',
  },
  {
    title: 'Blade & Sorcery',
    slug: 'blade-sorcery',
    description:
      'Blade and Sorcery — физическая песочница ближнего боя в фэнтезийном сеттинге: мечи, топоры, луки и стихийная магия взаимодействуют с противниками через реалистичную рэгдолл-физику. У игры нет сюжета — это арены и подземелья с волнами врагов, где можно экспериментировать с оружием, телекинезом и заклинаниями. Благодаря детализированным повреждениям бои выглядят зрелищно и очень натуралистично (присутствуют кровь и расчленение).',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1',
    age: '12',
    playtime: '15-30',
    maxPlayers: 1,
    popularity: 92,
    image: '/images/games/blade-sorcery.jpg',
    cover: '/images/games/covers/blade-sorcery.jpg',
    youtube: 'https://www.youtube.com/watch?v=-Kmd07gEq1s',
  },
  {
    title: 'Half-Life: Alyx',
    slug: 'half-life-alyx',
    description:
      'Half-Life: Alyx — полноценная VR-игра от Valve, приквел ко второй части Half-Life, где Аликс Вэнс сражается с силами Альянса и мутировавшими существами в мрачном City 17. Игра сочетает атмосферный сюжет, головоломки и напряжённые перестрелки с очень достоверной физикой взаимодействия с предметами. Считается эталоном качества среди VR-игр.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1',
    age: '8',
    playtime: '',
    maxPlayers: 1,
    popularity: 90,
    image: '/images/games/half-life-alyx.jpg',
    cover: '/images/games/covers/half-life-alyx.jpg',
    youtube: 'https://www.youtube.com/watch?v=ilk-6zD3M0A',
  },
  {
    title: 'I Am Cat',
    slug: 'i-am-cat',
    description:
      'I Am Cat — комедийный симулятор кота в VR: игрок вживается в роль пушистого хулигана в доме бабушки и устраивает контролируемый хаос — сбрасывает предметы с полок, царапает мебель, охотится и прячется. Игра семейная, лёгкая и юмористическая, с элементами песочницы и свободного исследования локаций.',
    genre: 'sim',
    platforms: ['pc'],
    players: '1',
    age: '6',
    playtime: '',
    maxPlayers: 1,
    popularity: 87,
    image: '/images/games/i-am-cat.jpg',
    cover: '/images/games/covers/i-am-cat.jpg',
    youtube: 'https://www.youtube.com/watch?v=CQlUqhiBk6Q',
  },
  {
    title: 'Minecraft',
    slug: 'minecraft',
    description:
      'Классический Minecraft, запущенный в VR через мод Vivecraft (ПК) или QuestCraft (автономно на Quest) — блочная песочница, где игрок буквально находится внутри своего мира: строит, добывает ресурсы, сражается с мобами. В VR привычный мир воспринимается совершенно иначе за счёт ощущения масштаба и погружения.',
    genre: 'sim',
    platforms: ['pc'],
    players: '1-10',
    age: '6',
    playtime: '15-30',
    maxPlayers: 10,
    popularity: 85,
    image: '/images/games/minecraft.jpg',
    cover: '/images/games/covers/minecraft.jpg',
    youtube: 'https://www.youtube.com/watch?v=tVLYzbT3AS0',
  },
  {
    title: 'Roblox',
    slug: 'roblox',
    description:
      'Roblox — это огромная платформа с миллионами пользовательских игр и миров, доступная в VR через Meta Quest и SteamVR. В VR-режиме это не одна игра, а портал в сотни разных мини-игр и социальных пространств — от гонок до хорроров и симуляторов.',
    genre: 'sim',
    platforms: ['pc'],
    players: '1-10',
    age: '6',
    playtime: '',
    maxPlayers: 10,
    popularity: 85,
    image: '/images/games/roblox.jpg',
    cover: '/images/games/covers/roblox.jpg',
    youtube: 'https://www.youtube.com/watch?v=d4c8_v02Fu8',
  },
  {
    title: 'BONELAB',
    slug: 'bonelab',
    description:
      'Bonelab — физический VR-экшен от создателей Boneworks с реалистичной симуляцией тела и предметов, головоломками и боями, где почти любой объект можно использовать как оружие. Игра сочетает исследование мрачных индустриальных локаций с песочницей, где можно призывать аватары и экспериментировать с физикой. Из-за сложного управления и местами тревожной атмосферы требует определённого VR-опыта.',
    genre: 'sim',
    platforms: ['pc'],
    players: '1',
    age: '8',
    playtime: '',
    maxPlayers: 1,
    popularity: 83,
    image: '/images/games/bonelab.jpg',
    cover: '/images/games/covers/bonelab.jpg',
    youtube: 'https://www.youtube.com/watch?v=aid65EZPyyM',
  },
  {
    title: 'I Am Security',
    slug: 'i-am-security',
    description:
      'I Am Security — юмористический VR-симулятор охранника ночного клуба: нужно проверять посетителей металлоискателем, изымать запрещённые предметы, следить за внешним видом и порядком на входе. Игра сочетает абсурдный юмор с механикой «сортировки» гостей, что особенно забавно смотрится именно в контексте настоящего клуба.',
    genre: 'sim',
    platforms: ['standalone'],
    players: '1',
    age: '12',
    playtime: '',
    maxPlayers: 1,
    popularity: 82,
    image: '/images/games/i-am-security.jpg',
    cover: '/images/games/covers/i-am-security.jpg',
    youtube: 'https://www.youtube.com/watch?v=Oik7DhtOU5Q',
  },
  {
    title: 'BONEWORKS',
    slug: 'boneworks',
    description:
      'Экспериментальный физический VR-экшен от Stress Level Zero, известный полностью физическим взаимодействием с оружием, предметами и собственным телом персонажа. Сочетает шутер, паркур и головоломки в мрачной sci-fi лаборатории. Атмосфера напряжённая и местами пугающая.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1',
    age: '10',
    playtime: '30-60',
    maxPlayers: 1,
    popularity: 79,
    image: '/images/games/boneworks.jpg',
    cover: '/images/games/covers/boneworks.jpg',
    youtube: 'https://www.youtube.com/watch?v=oP8C2nmv3Ag',
  },
  {
    title: 'Five Nights at Freddy\'s: Help Wanted',
    slug: 'five-nights-at-freddys-help-wanted',
    description:
      'Five Nights at Freddy\'s: Help Wanted — VR-хоррор по мотивам культовой серии, представляющий собой сборник мини-игр, где нужно выживать против аниматроников, следя за камерами и запирая двери. Атмосфера гнетущая, с внезапными скримерами и нарастающим напряжением. Понравится любителям хорроров и фанатам оригинальной серии FNAF.',
    genre: 'horror',
    platforms: ['pc'],
    players: '1',
    age: '10',
    playtime: '',
    maxPlayers: 1,
    popularity: 76,
    image: '/images/games/five-nights-at-freddys-help-wanted.jpg',
    cover: '/images/games/covers/five-nights-at-freddys-help-wanted.jpg',
    youtube: 'https://www.youtube.com/watch?v=lLv3wTRJwWM',
  },
  {
    title: 'Propagation VR',
    slug: 'propagation-vr',
    description:
      'Propagation VR — бесплатный VR-шутер в жанре survival horror, где игрок застревает на заброшенной станции метро, кишащей зомби и мутантами. Персонаж неподвижен, но должен отбивать волны врагов пистолетом и дробовиком, экономя патроны. Атмосфера мрачная, напряжённая, с внезапными скримерами. Есть режим кооператива на двоих.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1-2',
    age: '12',
    playtime: '30-60',
    maxPlayers: 2,
    popularity: 76,
    image: '/images/games/propagation-vr.jpg',
    cover: '/images/games/covers/propagation-vr.jpg',
    youtube: 'https://www.youtube.com/watch?v=TbTF1u6vHho',
  },
  {
    title: 'Superhot VR',
    slug: 'superhot-vr',
    description:
      'Культовый VR-шутер, в котором время движется только тогда, когда двигается сам игрок. Нужно уклоняться от пуль, разоружать врагов и планировать каждое движение как хореографию в почти застывшем времени — минималистичная стилистика и напряжённый, но контролируемый экшн.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1',
    age: '10',
    playtime: '30-60',
    maxPlayers: 1,
    popularity: 76,
    image: '/images/games/superhot-vr.jpg',
    cover: '/images/games/covers/superhot-vr.jpg',
    youtube: 'https://www.youtube.com/watch?v=pzG7Wc6mbwE',
  },
  {
    title: 'I Am Monkey',
    slug: 'i-am-monkey',
    description:
      'I Am Monkey — комедийная VR-песочница, в которой игрок вживается в роль обезьяны из зоопарка и взаимодействует с посетителями — от добрых до откровенно раздражающих. Жанр — казуальный симулятор-песочница с элементами хаоса и чёрного юмора; атмосфера смешная и абсурдная.',
    genre: 'sim',
    platforms: ['standalone'],
    players: '1',
    age: '12',
    playtime: '',
    maxPlayers: 1,
    popularity: 75,
    image: '/images/games/i-am-monkey.jpg',
    cover: '/images/games/covers/i-am-monkey.jpg',
    youtube: 'https://www.youtube.com/watch?v=LJCfvsjFybM',
  },
  {
    title: 'Job Simulator',
    slug: 'job-simulator',
    description:
      'Job Simulator — юмористический VR-симулятор от Owlchemy Labs: в мире, где всю работу выполняют роботы, игрок «переживает» будни офисного клерка, повара, продавца магазина или автомеханика. Игра отличается мультяшной графикой, абсурдным юмором и полной свободой взаимодействия с предметами. Один из лучших вариантов для первого знакомства с VR.',
    genre: 'sim',
    platforms: ['pc'],
    players: '1',
    age: '6',
    playtime: '30-60',
    maxPlayers: 1,
    popularity: 75,
    image: '/images/games/job-simulator.jpg',
    cover: '/images/games/covers/job-simulator.jpg',
    youtube: 'https://www.youtube.com/watch?v=8H9ieJk8AJ4',
  },
  {
    title: 'Elven Assassin',
    slug: 'elven-assassin',
    description:
      'Elven Assasin — аркадная VR-стрелялка из лука в жанре tower defense: игрок защищает город от волн орков и других врагов, отстреливаясь с одной из статичных позиций. Есть одиночный режим на рекорд, кооператив на 2-4 игрока и PvP-дезматч. Атмосфера лёгкая, фэнтезийная, без излишней жестокости.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1-4, 1-8',
    age: '6',
    playtime: '30-60',
    maxPlayers: 8,
    popularity: 72,
    image: '/images/games/elven-assassin.jpg',
    cover: '/images/games/covers/elven-assassin.jpg',
    youtube: 'https://www.youtube.com/watch?v=E2JaKeRpERI',
  },
  {
    title: 'GORN',
    slug: 'gorn',
    description:
      'GORN — комичный и предельно жестокий VR-симулятор гладиаторских боёв на физике: враги разлетаются, оружие деформируется, а кровь льётся рекой в мультяшном стиле. Игрок сражается голыми руками или разнообразным оружием против волн противников на арене. Управление завязано на реальных движениях рук, что делает бои физически ощутимыми и очень смешными.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1',
    age: '10',
    playtime: '15-30',
    maxPlayers: 1,
    popularity: 71,
    image: '/images/games/gorn.jpg',
    cover: '/images/games/covers/gorn.jpg',
    youtube: 'https://www.youtube.com/watch?v=cfGmGI0T48A',
  },
  {
    title: 'Walkabout Mini Golf VR',
    slug: 'walkabout-mini-golf-vr',
    description:
      'Walkabout Mini Golf VR — уютный мультиплеерный мини-гольф в виртуальной реальности с десятками красочных тематических полей: от готических замков до затерянных островов и марсианских садов. Игра отличается реалистичной физикой мяча, спокойной атмосферой и множеством пасхалок и секретов на каждой площадке. Можно играть в одиночку или компанией до восьми человек, в том числе кроссплатформенно с гостями на других VR-шлемах.',
    genre: 'sport',
    platforms: ['pc'],
    players: '1-8',
    age: '8',
    playtime: '',
    maxPlayers: 8,
    popularity: 71,
    image: '/images/games/walkabout-mini-golf-vr.jpg',
    cover: '/images/games/covers/walkabout-mini-golf-vr.jpg',
    youtube: 'https://www.youtube.com/watch?v=wyRjHU7vNEg',
  },
  {
    title: 'Arizona Sunshine',
    slug: 'arizona-sunshine',
    description:
      'Arizona Sunshine — кооперативный VR-шутер про выживание в зомби-апокалипсисе на фоне пустынь американского юго-запада. Игрок отстреливает орды зомби, реалистично перезаряжая оружие руками, в одиночку или вместе с друзьями (до 4 игроков). Атмосфера мрачная и напряжённая, с элементами чёрного юмора.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1-2, 1-4',
    age: '10',
    playtime: '',
    maxPlayers: 4,
    popularity: 70,
    image: '/images/games/arizona-sunshine.jpg',
    cover: '/images/games/covers/arizona-sunshine.jpg',
    youtube: 'https://www.youtube.com/watch?v=7K-DsESvTHo',
  },
  {
    title: 'Shave & Stuff',
    slug: 'shave-stuff',
    description:
      'Shave & Stuff — расслабляющий VR-симулятор барбершопа и тату-салона: игрок стрижёт, бреет, отращивает и красит волосы клиентам, создаёт причёски любой сложности, а также делает временные татуировки. Геймплей казуальный, почти ASMR-стиля, с добрым юмором и полной творческой свободой.',
    genre: 'sim',
    platforms: ['pc'],
    players: '1',
    age: '6',
    playtime: '',
    maxPlayers: 1,
    popularity: 70,
    image: '/images/games/shave-stuff.jpg',
    cover: '/images/games/covers/shave-stuff.jpg',
    youtube: 'https://www.youtube.com/watch?v=Bjf2JIHV-88',
  },
  {
    title: 'Pistol Whip',
    slug: 'pistol-whip',
    description:
      'Pistol Whip — гибрид VR-шутера и ритм-игры: игрок автоматически движется по стилизованной сцене в комикс-стиле, отстреливая врагов и уклоняясь от пуль в такт музыке. Каждый уровень — это отдельный музыкальный трек с нарастающим темпом и зрелищной хореографией движений. Игра динамичная, энергичная и отлично подходит как фитнес-активность.',
    genre: 'rhythm',
    platforms: ['pc'],
    players: '1',
    age: '6',
    playtime: '',
    maxPlayers: 1,
    popularity: 69,
    image: '/images/games/pistol-whip.jpg',
    cover: '/images/games/covers/pistol-whip.jpg',
    youtube: 'https://www.youtube.com/watch?v=WesN524L7hw',
  },
  {
    title: 'Five Nights at Freddy\'s: Help Wanted 2',
    slug: 'five-nights-at-freddys-help-wanted-2',
    description:
      'VR-хоррор по вселенной Five Nights at Freddy\'s (Help Wanted 2): игрок проходит серию мини-игр и заданий на территории аниматронного парка развлечений Fazbear Entertainment. Атмосфера жуткого джампскейр-хоррора с узнаваемыми аниматрониками и напряжённым саунд-дизайном.',
    genre: 'horror',
    platforms: ['pc'],
    players: '1',
    age: '10',
    playtime: '',
    maxPlayers: 1,
    popularity: 64,
    image: '/images/games/five-nights-at-freddys-help-wanted-2.jpg',
    cover: '/images/games/covers/five-nights-at-freddys-help-wanted-2.jpg',
    youtube: 'https://www.youtube.com/watch?v=jJ-1vXp7_0Q',
  },
  {
    title: 'After the Fall',
    slug: 'after-the-fall',
    description:
      'After the Fall — динамичный кооперативный VR-шутер от Vertigo Games (создателей Arizona Sunshine), действие которого разворачивается в альтернативных 1980-х после наступления ледникового периода. До четырёх игроков вместе исследуют заснеженные руины, крафтят и улучшают оружие, отбиваясь от толп агрессивных мутантов-снежников. Игра интенсивная, с упором на командную стрельбу и выживание.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1-4, 1-8',
    age: '10',
    playtime: '',
    maxPlayers: 8,
    popularity: 61,
    image: '/images/games/after-the-fall.jpg',
    cover: '/images/games/covers/after-the-fall.jpg',
    youtube: 'https://www.youtube.com/watch?v=qDclZNYOEf8',
  },
  {
    title: 'Pets & Stuff',
    slug: 'pets-stuff',
    description:
      'Pets & Stuff — уютный VR-симулятор ветеринара и грумера, где игрок ухаживает за милыми животными: моет, стрижёт и лечит котов, собак, лис и других зверей в нескольких локациях. Жанр — казуальный симулятор. Атмосфера расслабляющая, добрая и семейная.',
    genre: 'sim',
    platforms: ['pc'],
    players: '1',
    age: '6',
    playtime: '',
    maxPlayers: 1,
    popularity: 61,
    image: '/images/games/pets-stuff.jpg',
    cover: '/images/games/covers/pets-stuff.jpg',
    youtube: 'https://www.youtube.com/watch?v=w-TY0_MFUD0',
  },
  {
    title: 'TAXI DRIVER VR',
    slug: 'taxi-driver-vr',
    description:
      'TAXI DRIVER VR — весёлая песочница про таксиста: игрок подбирает пассажиров, машину ведёт автопилот, а всё самое интересное происходит на заднем сиденье. Пассажиров можно разговорить, успокоить, подразнить или просто наблюдать за их выходками — они танцуют, дерутся и выдают странные просьбы, вплоть до выдавливания прыщей. На заработанное покупаются инструменты и улучшения для машины. Смешная мультяшная игра без серьёзной драмы.',
    genre: 'sim',
    platforms: ['standalone'],
    players: '1',
    age: '12',
    playtime: '',
    maxPlayers: 1,
    popularity: 61,
    image: '/images/games/taxi-driver-vr.jpg',
    cover: '/images/games/covers/taxi-driver-vr.jpg',
    youtube: 'https://www.youtube.com/watch?v=FAx3u_GF28Q',
  },
  {
    title: 'Arizona Sunshine 2',
    slug: 'arizona-sunshine-2',
    description:
      'Arizona Sunshine 2 — кооперативный VR-шутер на выживание в мире, заполненном зомби. Игроки исследуют пустоши Аризоны в одиночку или с напарником (включая нового спутника — пса Рекса), отбиваясь от полчищ нежити огромным арсеналом оружия. Атмосфера мрачная и напряжённая, с фирменным для серии чёрным юмором.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1-2, 1-4',
    age: '10',
    playtime: '',
    maxPlayers: 4,
    popularity: 60,
    image: '/images/games/arizona-sunshine-2.jpg',
    cover: '/images/games/covers/arizona-sunshine-2.jpg',
    youtube: 'https://www.youtube.com/watch?v=j8afR1UeR6I',
  },
  {
    title: 'Epic Roller Coasters',
    slug: 'epic-roller-coasters',
    description:
      'Виртуальные американские горки с несколькими режимами — классическая поездка, стрельба по мишеням и гонки — на разнообразных тематических трассах от готических замков до подводных пещер. Одно из самых зрелищных и доступных VR-развлечений для новых гостей клуба, не требующее навыков.',
    genre: 'relax',
    platforms: ['pc'],
    players: '1',
    age: '6',
    playtime: '10-15',
    maxPlayers: 1,
    popularity: 60,
    image: '/images/games/epic-roller-coasters.jpg',
    cover: '/images/games/covers/epic-roller-coasters.jpg',
    youtube: 'https://www.youtube.com/watch?v=FUN84gPVpRs',
  },
  {
    title: 'Space Pirate Trainer',
    slug: 'space-pirate-trainer',
    description:
      'Space Pirate Trainer — динамичный аркадный VR-шутер, где игрок отбивается от волн дронов-роботов бластерами и энергетическим щитом в открытом космическом пространстве. Одна из классических демо-игр VR, известная чистым геймплеем и быстрым темпом. Атмосфера — яркий научно-фантастический экшен без сюжета, ориентированный на азарт и рекорды.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1',
    age: '6',
    playtime: '',
    maxPlayers: 1,
    popularity: 60,
    image: '/images/games/space-pirate-trainer.jpg',
    cover: '/images/games/covers/space-pirate-trainer.jpg',
    youtube: 'https://www.youtube.com/watch?v=xfa9Jqm34b0',
  },
  {
    title: 'Vacation Simulator',
    slug: 'vacation-simulator',
    description:
      'Vacation Simulator — юмористический VR-симулятор отдыха от создателей Job Simulator, где роботы будущего воссоздают человеческий отпуск на пляже, в горах и в лесу. Жанр — казуальная песочница/симулятор. Атмосфера яркая, доброжелательная и комичная, отлично подходит для новичков.',
    genre: 'sim',
    platforms: ['pc'],
    players: '1',
    age: '6',
    playtime: '15-30',
    maxPlayers: 1,
    popularity: 60,
    image: '/images/games/vacation-simulator.jpg',
    cover: '/images/games/covers/vacation-simulator.jpg',
    youtube: 'https://www.youtube.com/watch?v=9io7Zkoyxcw',
  },
  {
    title: 'Synth Riders',
    slug: 'synth-riders',
    description:
      'Synth Riders — VR-ритм-игра, в которой нужно ловить руками ноты и уклоняться от препятствий в такт музыке, сочетая элементы танца с лёгкой физической нагрузкой. Библиотека треков разнообразна — от электроники и синтвейва до лицензированных хитов известных исполнителей. Игра яркая, музыкальная и подходит как для соревнования, так и для разминки.',
    genre: 'rhythm',
    platforms: ['standalone'],
    players: '1',
    age: '12',
    playtime: '',
    maxPlayers: 1,
    popularity: 58,
    image: '/images/games/synth-riders.jpg',
    cover: '/images/games/covers/synth-riders.jpg',
    youtube: 'https://www.youtube.com/watch?v=lSQW_Amdo-g',
  },
  {
    title: 'Serious Sam: Last Hope',
    slug: 'serious-sam-last-hope',
    description:
      'Аркадный VR-шутер от Croteam из спин-оффа культовой серии Serious Sam. Игрок отбивается от полчищ гротескных монстров разнообразным оружием в напряжённых волновых сражениях. Динамичная, юмористическая и очень «мясная» атмосфера классического аркадного шутера.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1-2',
    age: '8',
    playtime: '30-60',
    maxPlayers: 2,
    popularity: 57,
    image: '/images/games/serious-sam-last-hope.jpg',
    cover: '/images/games/covers/serious-sam-last-hope.jpg',
    youtube: 'https://www.youtube.com/watch?v=EyMSCNafpOw',
  },
  {
    title: 'Devour',
    slug: 'devour',
    description:
      'Devour — кооперативный VR-хоррор на выживание для 1–4 игроков, где нужно выполнять ритуалы и собирать предметы, спасаясь от одержимой демонической куклы и других угроз. Жанр — survival-horror. Атмосфера пугающая, наполнена внезапными скримерами и погонями.',
    genre: 'horror',
    platforms: ['pc'],
    players: '1-4',
    age: '14',
    playtime: '',
    maxPlayers: 4,
    popularity: 56,
    image: '/images/games/devour.jpg',
    cover: '/images/games/covers/devour.jpg',
    youtube: 'https://www.youtube.com/watch?v=K6698E4mkYs',
  },
  {
    title: 'Hyper Dash',
    slug: 'hyper-dash',
    description:
      'Hyper Dash — динамичный командный VR-шутер в стиле арены, где игроки соревнуются 5 на 5 в режимах захвата флага, контроля точек и командного боя. Отличительная черта — свобода передвижения: рывки (dash), спринт и катание по рельсам позволяют молниеносно перемещаться по картам. Игра быстрая, соревновательная и требует активных физических движений.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1-10',
    age: '8',
    playtime: '',
    maxPlayers: 10,
    popularity: 56,
    image: '/images/games/hyper-dash.jpg',
    cover: '/images/games/covers/hyper-dash.jpg',
    youtube: 'https://www.youtube.com/watch?v=pDtHQgCzVoc',
  },
  {
    title: 'Richie\'s Plank Experience',
    slug: 'richies-plank-experience',
    description:
      'Richie\'s Plank Experience — культовый VR-аттракцион, имитирующий прогулку по доске на высоте небоскрёба. За счёт реалистичной физики и эффекта высоты игра вызывает настоящий страх, а при наличии в клубе физической доски ощущения становятся ещё более правдоподобными. Помимо основного режима есть дополнительные активности вроде вертолёта и пожарной машины.',
    genre: 'relax',
    platforms: ['pc'],
    players: '1',
    age: '10',
    playtime: '10-15',
    maxPlayers: 1,
    popularity: 56,
    image: '/images/games/richies-plank-experience.jpg',
    cover: '/images/games/covers/richies-plank-experience.jpg',
    youtube: 'https://www.youtube.com/watch?v=ImbhUHhWmSM',
  },
  {
    title: 'Blaston',
    slug: 'blaston',
    description:
      'Динамичная PvP-дуэльная VR-игра от Resolution Games: два игрока уклоняются от снарядов и одновременно атакуют друг друга футуристическим оружием в почти замедленном темпе. Похоже на боевой балет — важны реакция, приседания и уклонения корпусом, а не прицельная стрельба.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1-2',
    age: '8',
    playtime: '',
    maxPlayers: 2,
    popularity: 54,
    image: '/images/games/blaston.jpg',
    cover: '/images/games/covers/blaston.jpg',
    youtube: 'https://www.youtube.com/watch?v=v8JTy12r68Q',
  },
  {
    title: 'Red Matter 2',
    slug: 'red-matter-2',
    description:
      'Атмосферный сай-фай квест-пазл в сеттинге альтернативной холодной войны в космосе: агент Саша исследует лунную базу и другие локации, решает головоломки, летает на джетпаке в невесомости и проходит стелс-эпизоды. Одна из самых красивых VR-игр с кинематографичным повествованием.',
    genre: 'quest',
    platforms: ['standalone'],
    players: '1',
    age: '12',
    playtime: '',
    maxPlayers: 1,
    popularity: 54,
    image: '/images/games/red-matter-2.jpg',
    cover: '/images/games/covers/red-matter-2.jpg',
    youtube: 'https://www.youtube.com/watch?v=teqia7GJ_iE',
  },
  {
    title: 'Drop Dead: The Cabin',
    slug: 'drop-dead-the-cabin',
    description:
      'Drop Dead: The Cabin — напряжённый шутер на выживание: игрок заперт в хижине посреди леса и отбивается от волн жутких существ, которые лезут через каждую дверь и окно. Нужно искать припасы и оружие и держать оборону как можно дольше. Жёсткая игра для старших игроков.',
    genre: 'shooter',
    platforms: ['standalone'],
    players: '1',
    age: '14',
    playtime: '',
    maxPlayers: 1,
    popularity: 53,
    image: '/images/games/drop-dead-the-cabin.jpg',
    cover: '/images/games/covers/drop-dead-the-cabin.jpg',
    youtube: 'https://www.youtube.com/watch?v=cmrd5FyTmAs',
  },
  {
    title: 'The Climb 2',
    slug: 'the-climb-2',
    description:
      'The Climb 2 — VR-симулятор скалолазания от Crytek, где игрок карабкается по скалам, небоскрёбам и пещерам, аккуратно рассчитывая каждый хват руками. Игра сочетает медитативные виды с высоты и напряжение от риска сорваться вниз. Хорошо передаёт ощущение реального скалолазания без физической нагрузки.',
    genre: 'sport',
    platforms: ['standalone'],
    players: '1',
    age: '6',
    playtime: '',
    maxPlayers: 1,
    popularity: 53,
    image: '/images/games/the-climb-2.jpg',
    cover: '/images/games/covers/the-climb-2.jpg',
    youtube: 'https://www.youtube.com/watch?v=FzWgYEpQjVA',
  },
  {
    title: 'Arizona Sunshine Remake',
    slug: 'arizona-sunshine-remake',
    description:
      'Полностью переработанный VR-шутер про выживание в зомби-апокалипсисе среди пустынь Аризоны. Игрок сражается с ордами зомби в одиночку или в кооперативе до четырёх человек, используя реалистичную физику оружия и перезарядку вручную. Атмосфера напряжённого survival-horror с чёрным юмором и постапокалиптическими пейзажами.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1-2, 1-4',
    age: '10',
    playtime: '',
    maxPlayers: 4,
    popularity: 52,
    image: '/images/games/arizona-sunshine-remake.jpg',
    cover: '/images/games/covers/arizona-sunshine-remake.jpg',
    youtube: 'https://www.youtube.com/watch?v=A0sfvHUynOI',
  },
  {
    title: 'Cooking Simulator VR',
    slug: 'cooking-simulator-vr',
    description:
      'Cooking Simulator VR — физический симулятор кухни с более чем сотней рецептов и множеством ингредиентов, где можно готовить реалистично или устраивать кулинарный хаос с пожарами и взрывами. Игра сочетает обучающий кулинарный геймплей с песочницей для свободных экспериментов.',
    genre: 'sim',
    platforms: ['standalone'],
    players: '1',
    age: '6',
    playtime: '',
    maxPlayers: 1,
    popularity: 52,
    image: '/images/games/cooking-simulator-vr.jpg',
    cover: '/images/games/covers/cooking-simulator-vr.jpg',
    youtube: 'https://www.youtube.com/watch?v=iu0k2JX9RsA',
  },
  {
    title: 'Deisim',
    slug: 'deisim',
    description:
      'Deisim — VR-симулятор бога, в котором игрок с высоты птичьего полёта управляет землёй, ресурсами и развитием цивилизации от каменного века до наших дней. Жанр — песочница-стратегия в духе Populous и Black & White; атмосфера созерцательная и масштабная.',
    genre: 'sim',
    platforms: ['pc'],
    players: '1',
    age: '6',
    playtime: '',
    maxPlayers: 1,
    popularity: 52,
    image: '/images/games/deisim.jpg',
    cover: '/images/games/covers/deisim.jpg',
    youtube: 'https://www.youtube.com/watch?v=6O80bMSR570',
  },
  {
    title: 'PAYDAY 2 VR',
    slug: 'payday-2-vr',
    description:
      'PAYDAY 2 VR — кооперативный VR-шутер про ограбления: игроки планируют и выполняют дерзкие налёты на банки, ювелирные магазины и инкассаторов. Атмосфера напряжённая — нужно следить за камерами, заложниками и полицией, которая быстро прибывает на шум. Жанр сочетает стелс-элементы и тактический кооператив на 4 игроков.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1-4',
    age: '12',
    playtime: '30-60',
    maxPlayers: 4,
    popularity: 52,
    image: '/images/games/payday-2-vr.jpg',
    cover: '/images/games/covers/payday-2-vr.jpg',
    youtube: 'https://www.youtube.com/watch?v=_RfYqSh-RG0',
  },
  {
    title: 'Raw Data',
    slug: 'raw-data',
    description:
      'Raw Data — динамичный кооперативный VR-шутер от Survios, в котором игроки в роли героев с уникальными способностями (стрелки, ниндзя с катаной и телекинезом) отражают волны роботов корпорации Eden Corp. Доступны одиночная игра и кооператив до 4 человек с прокачкой персонажей между волнами. Экшен зрелищный, сочетает стрельбу и ближний бой.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1-2, 1-10',
    age: '12',
    playtime: '',
    maxPlayers: 10,
    popularity: 51,
    image: '/images/games/raw-data.jpg',
    cover: '/images/games/covers/raw-data.jpg',
    youtube: 'https://www.youtube.com/watch?v=hwNvzI1TSTU',
  },
  {
    title: 'Resident Evil 7: Biohazard',
    slug: 'resident-evil-7-biohazard',
    description:
      'Хоррор от первого лица от Capcom, вернувший серию Resident Evil к survival-horror корням в особняке семьи Бейкеров. Официальный VR-режим доступен на PS4/PSVR, а на ПК VR реализуется через популярный мод Praydog. Атмосфера крайне пугающая и клаустрофобная, с внезапными скримерами.',
    genre: 'horror',
    platforms: ['pc'],
    players: '1',
    age: '14',
    playtime: '',
    maxPlayers: 1,
    popularity: 51,
    image: '/images/games/resident-evil-7-biohazard.jpg',
    cover: '/images/games/covers/resident-evil-7-biohazard.jpg',
    youtube: 'https://www.youtube.com/watch?v=eNquayO60Z8',
  },
  {
    title: 'Budget Cuts',
    slug: 'budget-cuts',
    description:
      'Budget Cuts — VR-стелс с элементами головоломки, в котором нужно незаметно проникать на этажи корпорации, уклоняясь от роботов-убийц, используя нож-портал для телепортации и метательное оружие. Жанр — стелс-экшен. Атмосфера напряжённая, с чёрным юмором и сатирой на офисную жизнь.',
    genre: 'quest',
    platforms: ['pc'],
    players: '1',
    age: '8',
    playtime: '',
    maxPlayers: 1,
    popularity: 50,
    image: '/images/games/budget-cuts.jpg',
    cover: '/images/games/covers/budget-cuts.jpg',
    youtube: 'https://www.youtube.com/watch?v=72s5zS982Vs',
  },
  {
    title: 'SCP: Labrat',
    slug: 'scp-labrat',
    description:
      'VR-хоррор, переосмысление культовой SCP - Containment Breach: игрок — подопытный в секретном исследовательском комплексе Фонда SCP, где во время побега аномальных объектов нужно выбраться живым, избегая опасных сущностей. Атмосфера напряжённого survival-horror со стелс-элементами и исследованием.',
    genre: 'horror',
    platforms: ['pc'],
    players: '1-2',
    age: '12',
    playtime: '',
    maxPlayers: 2,
    popularity: 49,
    image: '/images/games/scp-labrat.jpg',
    cover: '/images/games/covers/scp-labrat.jpg',
    youtube: 'https://www.youtube.com/watch?v=uFEDGi51gIU',
  },
  {
    title: 'GORN 2',
    slug: 'gorn-2',
    description:
      'Безумный VR-гладиаторский симулятор с рэгдолл-физикой от Free Lives, продолжение культовой GORN. Игрок сражается на арене с гротескными противниками, используя десятки видов оружия — от мечей до молотов, а вся боёвка построена на комично-жестокой физике. Очень активная, кровавая и юмористическая игра.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1',
    age: '10',
    playtime: '',
    maxPlayers: 1,
    popularity: 48,
    image: '/images/games/gorn-2.jpg',
    cover: '/images/games/covers/gorn-2.jpg',
    youtube: 'https://www.youtube.com/watch?v=hGROKh-1Bz8',
  },
  {
    title: 'Cook-Out: A Sandwich Tale',
    slug: 'cook-out-a-sandwich-tale',
    description:
      'Cook-Out — кооперативный VR-симулятор кулинарии от Resolution Games, где до четырёх игроков совместно готовят и подают блюда сказочным существам в уютной лесной хижине. Жанр — казуальный кооперативный экшен с элементами тайм-менеджмента; атмосфера дружелюбная, яркая и слегка безумная — шутники и воришки постоянно мешают работе.',
    genre: 'sim',
    platforms: ['pc'],
    players: '1-4',
    age: '8',
    playtime: '',
    maxPlayers: 4,
    popularity: 46,
    image: '/images/games/cook-out-a-sandwich-tale.jpg',
    cover: '/images/games/covers/cook-out-a-sandwich-tale.jpg',
    youtube: 'https://www.youtube.com/watch?v=ENN7KL7ZWEg',
  },
  {
    title: 'Ghost Town',
    slug: 'ghost-town',
    description:
      'Ghost Town — мистическое приключение с головоломками от Fireproof Games, авторов серии The Room. С фонарём в руке игрок исследует атмосферные места, встречает живых и призраков, решает загадки руками и помогает неупокоенным душам обрести покой. Неспешная история для любителей мистики и головоломок.',
    genre: 'quest',
    platforms: ['standalone'],
    players: '1',
    age: '12',
    playtime: '',
    maxPlayers: 1,
    popularity: 46,
    image: '/images/games/ghost-town.jpg',
    cover: '/images/games/covers/ghost-town.jpg',
    youtube: 'https://www.youtube.com/watch?v=052hBB-f_EY',
  },
  {
    title: 'Serious Sam Fusion 2017',
    slug: 'serious-sam-fusion-2017',
    description:
      '«Хаб»-версия классической серии Serious Sam от Croteam, объединяющая в одном лаунчере обычные и VR-версии нескольких игр (The First Encounter, The Second Encounter, Serious Sam 3). Позволяет мгновенно переключаться между режимами, модами и кооперативом. Безумный, юмористический шутер против бесконечных орд врагов.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1-16',
    age: '8',
    playtime: '',
    maxPlayers: 16,
    popularity: 46,
    image: '/images/games/serious-sam-fusion-2017.jpg',
    cover: '/images/games/covers/serious-sam-fusion-2017.jpg',
    youtube: 'https://www.youtube.com/watch?v=GssERn9JCJQ',
  },
  {
    title: 'Vermillion',
    slug: 'vermillion',
    description:
      'Спокойный VR-симулятор масляной живописи: игрок получает виртуальную студию художника с реалистичным смешиванием красок на палитре и рисованием на холсте. Расслабляющая, творческая, не соревновательная игра — подходит и новичкам, и опытным художникам.',
    genre: 'relax',
    platforms: ['standalone'],
    players: '1',
    age: '6',
    playtime: '',
    maxPlayers: 1,
    popularity: 46,
    image: '/images/games/vermillion.jpg',
    cover: '/images/games/covers/vermillion.jpg',
    youtube: 'https://www.youtube.com/watch?v=LniHnza8WZY',
  },
  {
    title: 'Golf 5',
    slug: 'golf-5',
    description:
      'Golf 5 — реалистичный VR-гольф, созданный при участии The R&A и DP World Tour: система точного управления фиксирует замах вплоть до миллиметра. Можно тренироваться, играть против компьютера или соревноваться онлайн и участвовать в турнирах. Подойдёт и новичкам, которые только знакомятся с гольфом, и тем, кто хочет отточить удар.',
    genre: 'sport',
    platforms: ['standalone'],
    players: '1',
    age: '6',
    playtime: '',
    maxPlayers: 1,
    popularity: 45,
    image: '/images/games/golf-5.jpg',
    cover: '/images/games/covers/golf-5.jpg',
    youtube: 'https://www.youtube.com/watch?v=zAjOUWKBmX0',
  },
  {
    title: 'Brazen Blaze',
    slug: 'brazen-blaze',
    description:
      'Brazen Blaze — динамичный VR-файтинг 3 на 3 в жанре «smack & shoot», сочетающий рукопашный ближний бой с использованием оружия и разрушаемые арены. Игра вдохновлена Super Smash Bros. и делает акцент на скорости и физическом взаимодействии игроков. Сейчас распространяется бесплатно (free-to-play).',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1-6',
    age: '10',
    playtime: '',
    maxPlayers: 6,
    popularity: 43,
    image: '/images/games/brazen-blaze.jpg',
    cover: '/images/games/covers/brazen-blaze.jpg',
    youtube: 'https://www.youtube.com/watch?v=i8h1TEj7Mgs',
  },
  {
    title: 'Tilt Brush',
    slug: 'tilt-brush',
    description:
      'Tilt Brush — творческое VR-приложение от Google, позволяющее рисовать трёхмерные картины прямо в воздухе с помощью контроллеров. Жанр — креативная песочница и арт-инструмент; атмосфера медитативная и вдохновляющая, без соревновательных элементов, подходит для свободного самовыражения.',
    genre: 'relax',
    platforms: ['pc'],
    players: '1',
    age: '6',
    playtime: '10-15',
    maxPlayers: 1,
    popularity: 43,
    image: '/images/games/tilt-brush.jpg',
    cover: '/images/games/covers/tilt-brush.jpg',
    youtube: 'https://www.youtube.com/watch?v=4eyOk2a-Nb4',
  },
  {
    title: 'Gladius',
    slug: 'gladius',
    description:
      'Gladius (Gladiator VR Sword fighting) — VR-игра про гладиаторские поединки в древнем Риме: игрок выбирает оружие и доспехи, тренируется против ботов и сражается на аренах с воинами и мифическими существами. Бои основаны на физике фехтования — важны реальные удары, блоки и уклонения корпусом. Есть режимы на выживание, рейтинговая арена и песочница для тренировок.',
    genre: 'shooter',
    platforms: ['standalone'],
    players: '1',
    age: '14',
    playtime: '',
    maxPlayers: 1,
    popularity: 41,
    image: '/images/games/gladius.jpg',
    cover: '/images/games/covers/gladius.jpg',
    youtube: 'https://www.youtube.com/watch?v=BuEMR81KWuQ',
  },
  {
    title: 'House Flipper VR',
    slug: 'house-flipper-vr',
    description:
      'House Flipper VR — спокойный симулятор ремонта и уборки: игрок восстанавливает заброшенные дома, моет, красит, чинит мебель и обставляет интерьер. Жанр — казуальная симуляция без стресса и таймеров, подходит для расслабленного времяпрепровождения. Атмосфера уютная и терапевтичная — нравится гостям, уставшим от динамичных шутеров.',
    genre: 'sim',
    platforms: ['pc'],
    players: '1',
    age: '6',
    playtime: '',
    maxPlayers: 1,
    popularity: 40,
    image: '/images/games/house-flipper-vr.jpg',
    cover: '/images/games/covers/house-flipper-vr.jpg',
    youtube: 'https://www.youtube.com/watch?v=Q7ut_w83Zto',
  },
  {
    title: 'Ocean Rift',
    slug: 'ocean-rift',
    description:
      'Ocean Rift — расслабляющий VR-аттракцион, погружающий игрока в подводный мир: коралловые рифы, акулы, киты, дельфины и даже доисторические существа. Это не игра с целями, а исследовательский опыт с образовательным режимом — идеальное знакомство с VR. Атмосфера умиротворяющая, подходит гостям любого возраста и опыта.',
    genre: 'relax',
    platforms: ['pc'],
    players: '1',
    age: '6',
    playtime: '10-15',
    maxPlayers: 1,
    popularity: 40,
    image: '/images/games/ocean-rift.jpg',
    cover: '/images/games/covers/ocean-rift.jpg',
    youtube: 'https://www.youtube.com/watch?v=tEE2VJq2_zc',
  },
  {
    title: 'The Talos Principle VR',
    slug: 'the-talos-principle-vr',
    description:
      'VR-адаптация философской головоломки от Croteam: игрок исследует руины древней цивилизации вперемешку с высокими технологиями, решая всё более сложные пазлы с лучами, коннекторами и порталами. Атмосфера созерцательная, с глубоким сюжетом о природе сознания и свободе воли.',
    genre: 'quest',
    platforms: ['pc'],
    players: '1',
    age: '12',
    playtime: '30-60',
    maxPlayers: 1,
    popularity: 39,
    image: '/images/games/the-talos-principle-vr.jpg',
    cover: '/images/games/covers/the-talos-principle-vr.jpg',
    youtube: 'https://www.youtube.com/watch?v=yBVoZ0X3a_0',
  },
  {
    title: 'Undead Citadel',
    slug: 'undead-citadel',
    description:
      'Undead Citadel — VR-экшен с физическим ближним боем в мрачном фэнтезийном мире, наводнённом нежитью, где нужно сражаться мечами, топорами, луками и другим оружием средневековья. Жанр — слэшер/экшен. Атмосфера мрачная, кровавая и динамичная, с упором на реалистичную физику ударов.',
    genre: 'shooter',
    platforms: ['standalone'],
    players: '1',
    age: '14',
    playtime: '',
    maxPlayers: 1,
    popularity: 39,
    image: '/images/games/undead-citadel.jpg',
    cover: '/images/games/covers/undead-citadel.jpg',
    youtube: 'https://www.youtube.com/watch?v=smd3TUFe2cg',
  },
  {
    title: 'All-in-One Sports VR',
    slug: 'all-in-one-sports-vr',
    description:
      'All-in-One Sports VR — сборник виртуальных видов спорта: бейсбол, боулинг, теннис, баскетбол, гольф, бильярд, дартс, бадминтон, бокс и другие активности. Игра ориентирована на активное движение и лёгкий фитнес в VR, без сюжета и с минимальным порогом входа. Атмосфера дружелюбная и казуальная — отлично подходит для группового посещения клуба.',
    genre: 'sport',
    platforms: ['pc'],
    players: '1-2',
    age: '6',
    playtime: '',
    maxPlayers: 2,
    popularity: 38,
    image: '/images/games/all-in-one-sports-vr.jpg',
    cover: '/images/games/covers/all-in-one-sports-vr.jpg',
    youtube: 'https://www.youtube.com/watch?v=Lva5G1a0kB0',
  },
  {
    title: 'Dead Second',
    slug: 'dead-second',
    description:
      'VR-аркадный тир от Spunge Games в духе классических рельсовых шутеров вроде Time Crisis и House of the Dead, с фирменной механикой замедления времени «Dead Second» для эффектных попаданий. Динамичный аркадный экшен с укрытиями и волнами врагов.',
    genre: 'shooter',
    platforms: ['standalone'],
    players: '1',
    age: '14',
    playtime: '',
    maxPlayers: 1,
    popularity: 38,
    image: '/images/games/dead-second.jpg',
    cover: '/images/games/covers/dead-second.jpg',
    youtube: 'https://www.youtube.com/watch?v=7X_4VVnMN2M',
  },
  {
    title: 'Outta Hand',
    slug: 'outta-hand',
    description:
      'Outta Hand — VR-платформер с необычной механикой передвижения: персонаж перемещается, размахивая длинными вытягивающимися руками, как по лианам. Игроку предстоит пройти десятки уровней лаборатории безумного доктора, победить боссов и отточить координацию. Атмосфера энергичная и с юмором, вызывает азарт.',
    genre: 'quest',
    platforms: ['pc'],
    players: '1',
    age: '8',
    playtime: '',
    maxPlayers: 1,
    popularity: 38,
    image: '/images/games/outta-hand.jpg',
    cover: '/images/games/covers/outta-hand.jpg',
    youtube: 'https://www.youtube.com/watch?v=GTC42LQngPE',
  },
  {
    title: 'Serious Sam VR: The First Encounter',
    slug: 'serious-sam-vr-the-first-encounter',
    description:
      'Serious Sam VR: The First Encounter — безумный аркадный VR-шутер от первого лица, переносящий классику Serious Sam в виртуальную реальность. Игрок отстреливает орды монстров на аренах в динамичном экшене с изрядной долей олдскульного юмора и драйва.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1-16',
    age: '8',
    playtime: '',
    maxPlayers: 16,
    popularity: 38,
    image: '/images/games/serious-sam-vr-the-first-encounter.jpg',
    cover: '/images/games/covers/serious-sam-vr-the-first-encounter.jpg',
    youtube: 'https://www.youtube.com/watch?v=UeIOUVVYKvU',
  },
  {
    title: 'Serious Sam 3 VR: BFE',
    slug: 'serious-sam-3-vr-bfe',
    description:
      'Serious Sam 3 VR: BFE — адаптация культового шутера от Croteam для виртуальной реальности, где игрок в одиночку противостоит ордам инопланетных монстров в Египте. Это чистый олдскульный экшен: десятки врагов одновременно, огромный арсенал оружия и никакого отсиживания в укрытии — только скорость и реакция. В VR ощущение масштаба и хаоса боя усиливается многократно.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1-16',
    age: '8',
    playtime: '',
    maxPlayers: 16,
    popularity: 36,
    image: '/images/games/serious-sam-3-vr-bfe.jpg',
    cover: '/images/games/covers/serious-sam-3-vr-bfe.jpg',
    youtube: 'https://www.youtube.com/watch?v=VO7HtOnqXd8',
  },
  {
    title: 'Surgeon Simulator VR: Meet The Medic',
    slug: 'surgeon-simulator-vr-meet-the-medic',
    description:
      'Surgeon Simulator VR: Meet The Medic — комедийный VR-симулятор хирургии по мотивам Team Fortress 2, где игрок в роли Медика пытается спасти Хэви, управляя нарочито неуклюжими руками. Жанр — юмористический симулятор-головоломка; атмосфера абсурдная и очень весёлая для зрителей.',
    genre: 'sim',
    platforms: ['pc'],
    players: '1',
    age: '6',
    playtime: '',
    maxPlayers: 1,
    popularity: 36,
    image: '/images/games/surgeon-simulator-vr-meet-the-medic.jpg',
    cover: '/images/games/covers/surgeon-simulator-vr-meet-the-medic.jpg',
    youtube: 'https://www.youtube.com/watch?v=CZBLMHJO6s4',
  },
  {
    title: 'Demeo Battles',
    slug: 'demeo-battles',
    description:
      'Demeo Battles — соревновательный PvP-спин-офф настольной ролевой стратегии Demeo: игроки управляют отрядом героев-миниатюр на клетчатой доске и сражаются друг против друга в пошаговых тактических боях. Игра доступна как в VR, так и на плоском экране, с кроссплатформенным мультиплеером. Атмосфера настольной игры с фэнтезийными классами героев (маг, воин, лучник и другие) и быстрыми раундами.',
    genre: 'party',
    platforms: ['standalone'],
    players: '1',
    age: '10',
    playtime: '',
    maxPlayers: 1,
    popularity: 32,
    image: '/images/games/demeo-battles.jpg',
    cover: '/images/games/covers/demeo-battles.jpg',
    youtube: 'https://www.youtube.com/watch?v=z0I0jMuIZdU',
  },
  {
    title: 'Sid Meier\'s Civilization VII — VR',
    slug: 'sid-meiers-civilization-vii-vr',
    description:
      'Sid Meier\'s Civilization VII — VR — версия знаменитой пошаговой стратегии для виртуальной реальности: империя строится за командным столом, где карта лежит перед игроком в объёме. Нужно развивать города, открывать технологии, вести дипломатию и воевать с соперниками. Неспешная и вдумчивая игра для любителей стратегий; работает только на Meta Quest 3 и 3S.',
    genre: 'party',
    platforms: ['standalone'],
    players: '1',
    age: '10',
    playtime: '',
    maxPlayers: 1,
    popularity: 30,
    image: '/images/games/sid-meiers-civilization-vii-vr.jpg',
    cover: '/images/games/covers/sid-meiers-civilization-vii-vr.jpg',
    youtube: 'https://www.youtube.com/watch?v=lavuwKvZki8',
  },
  {
    title: 'Serious Sam VR: The Second Encounter',
    slug: 'serious-sam-vr-the-second-encounter',
    description:
      'Serious Sam VR: The Second Encounter — безумный аркадный VR-шутер с толпами гротескных монстров и фирменным юмором серии. Игрок в одиночку или в кооперативе отстреливается от десятков врагов одновременно, используя большой арсенал оружия — от пистолета до пушки. Атмосфера динамичная, самоироничная и совершенно несерьёзная, несмотря на грозное название.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1-16',
    age: '8',
    playtime: '',
    maxPlayers: 16,
    popularity: 27,
    image: '/images/games/serious-sam-vr-the-second-encounter.jpg',
    cover: '/images/games/covers/serious-sam-vr-the-second-encounter.jpg',
    youtube: 'https://www.youtube.com/watch?v=s1E9myNYcms',
  },
  {
    title: 'Fancy Skiing VR',
    slug: 'fancy-skiing-vr',
    description:
      'Fancy Skiing VR — аркадный симулятор катания на лыжах, где игрок спускается по заснеженным трассам, объезжая препятствия и выполняя трюки. Управление имитирует реальные движения лыжника: отталкивание палками и повороты корпусом. Игра бодрая и динамичная, хорошо подходит как активное развлечение.',
    genre: 'sport',
    platforms: ['pc'],
    players: '1',
    age: '6',
    playtime: '10-15',
    maxPlayers: 1,
    popularity: 26,
    image: '/images/games/fancy-skiing-vr.jpg',
    cover: '/images/games/covers/fancy-skiing-vr.jpg',
    youtube: 'https://www.youtube.com/watch?v=rvtm8T14BRE',
  },
  {
    title: 'Loco Dojo',
    slug: 'loco-dojo',
    description:
      'Loco Dojo — весёлая VR-вечеринка для компании, где игроки соревнуются в шестнадцати абсурдных мини-играх на «Столе испытаний» под руководством Grand Sensei. Жанр — казуальная party-игра с элементами настольной игры; атмосфера яркая, комичная и азартная, рассчитана на смех и соперничество друзей.',
    genre: 'party',
    platforms: ['pc'],
    players: '1-4',
    age: '6',
    playtime: '',
    maxPlayers: 4,
    popularity: 26,
    image: '/images/games/loco-dojo.jpg',
    cover: '/images/games/covers/loco-dojo.jpg',
    youtube: 'https://www.youtube.com/watch?v=Iz2dGWHYn4Y',
  },
  {
    title: 'theBlu',
    slug: 'theblu',
    description:
      'theBlu — спокойный созерцательный VR-опыт погружения в океанские глубины, где гость встречается лицом к лицу с гигантским синим китом, коралловым рифом и обитателями глубин. Это не игра в привычном смысле, а атмосферная демонстрация масштаба и красоты подводного мира, ставшая одной из знаковых VR-демонстраций.',
    genre: 'relax',
    platforms: ['pc'],
    players: '1',
    age: '6',
    playtime: '10-15',
    maxPlayers: 1,
    popularity: 26,
    image: '/images/games/theblu.jpg',
    cover: '/images/games/covers/theblu.jpg',
    youtube: 'https://www.youtube.com/watch?v=z9HikzYojjU',
  },
  {
    title: 'CoasterMania',
    slug: 'coastermania',
    description:
      'VR-конструктор американских горок для Meta Quest с поддержкой смешанной реальности: игрок руками строит трассу прямо в своей комнате, а затем катается на ней от первого лица. Яркая, казуальная и семейная игра, сочетающая творчество с ощущениями настоящего аттракциона.',
    genre: 'relax',
    platforms: ['standalone'],
    players: '1',
    age: '6',
    playtime: '',
    maxPlayers: 1,
    popularity: 25,
    image: '/images/games/coastermania.jpg',
    cover: '/images/games/covers/coastermania.jpg',
    youtube: 'https://www.youtube.com/watch?v=BhOTi74y_fI',
  },
  {
    title: 'Figmin XR',
    slug: 'figmin-xr',
    description:
      'Figmin XR — творческое приложение смешанной реальности для создания, коллекционирования и оживления 3D-объектов прямо в своей комнате. Здесь нет привычных целей или уровней — это песочница для конструирования сцен, анимаций и совместного творчества в AR/VR.',
    genre: 'relax',
    platforms: ['standalone'],
    players: '1',
    age: '12',
    playtime: '',
    maxPlayers: 1,
    popularity: 25,
    image: '/images/games/figmin-xr.jpg',
    cover: '/images/games/covers/figmin-xr.jpg',
    youtube: 'https://www.youtube.com/watch?v=MB8DaHEioEc',
  },
  {
    title: 'All-in-One Summer Sports VR',
    slug: 'all-in-one-summer-sports-vr',
    description:
      'Сборник летних видов спорта в VR — бейсбол, теннис, боулинг, гольф, стрельба из лука, бадминтон, настольный теннис и другие дисциплины на одном тропическом острове. Игра рассчитана на активные движения руками и телом, подходит для семейного и группового досуга.',
    genre: 'sport',
    platforms: ['pc'],
    players: '1-5',
    age: '6',
    playtime: '',
    maxPlayers: 5,
    popularity: 17,
    image: '/images/games/all-in-one-summer-sports-vr.jpg',
    cover: '/images/games/covers/all-in-one-summer-sports-vr.jpg',
    youtube: 'https://www.youtube.com/watch?v=CGcsiA6KBMg',
  },
  {
    title: 'Private Property',
    slug: 'private-property',
    description:
      'Private Property — кооперативный VR-шутер с элементами tower defense в декорациях вестерна: действие происходит на ранчо конца XIX века в Монтане, где нужно отбиваться от волн зомби. Игроки в одиночку или командой до восьми человек используют разнообразное огнестрельное оружие и укрепления, чтобы защитить территорию между волнами противников. Атмосфера лёгкая и аркадная, с юмором, несмотря на тематику зомби-апокалипсиса.',
    genre: 'shooter',
    platforms: ['pc'],
    players: '1-8',
    age: '10',
    playtime: '',
    maxPlayers: 8,
    popularity: 13,
    image: '/images/games/private-property.jpg',
    cover: '/images/games/covers/private-property.jpg',
    youtube: 'https://www.youtube.com/watch?v=Gq0LHRQzWcQ',
  },
];
